-------------------------------------------------------------------------------
Test set: cat.institutmarianao.gymtony.test.UsuarioServiceImplTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 0.323 s <<< FAILURE! -- in cat.institutmarianao.gymtony.test.UsuarioServiceImplTest
cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenUserNotFoundByUsername -- Time elapsed: 0.211 s <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenUserNotFoundByUsername(UsuarioServiceImplTest.java:159)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldRemoveUser -- Time elapsed: 0.034 s <<< FAILURE!
Wanted but not invoked:
usuarioRepository.delete(
    Usuario(id=null, username=testuser, password=password, name=Test User, dni=12345678A, email=test@example.com, age=25, role=CLIENTE, confirmPassword=null)
);
-> at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldRemoveUser(UsuarioServiceImplTest.java:132)

However, there was exactly 1 interaction with this mock:
usuarioRepository.deleteByUsername(
    "testuser"
);
-> at cat.institutmarianao.gymtony.services.impl.UsuarioServiceImpl.remove(UsuarioServiceImpl.java:89)


	at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldRemoveUser(UsuarioServiceImplTest.java:132)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenUpdatingNonExistentUser -- Time elapsed: 0.005 s <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenUpdatingNonExistentUser(UsuarioServiceImplTest.java:121)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenRemovingNonExistentUser -- Time elapsed: 0.005 s <<< FAILURE!
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldThrowExceptionWhenRemovingNonExistentUser(UsuarioServiceImplTest.java:139)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldUpdateUserAndEncryptPasswordIfChanged -- Time elapsed: 0.009 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "hashedNewPassword"
 but was: "newPassword"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at cat.institutmarianao.gymtony.test.UsuarioServiceImplTest.shouldUpdateUserAndEncryptPasswordIfChanged(UsuarioServiceImplTest.java:113)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

